CREATE TABLE USER (
  USER_ID              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  EMAIL                VARCHAR(50)  NULL     DEFAULT NULL,
  PASSWORD             VARCHAR(60)  NULL     DEFAULT NULL,
  CITY                 VARCHAR(175) NULL     DEFAULT NULL,
  COUNTRY              VARCHAR(175) NULL     DEFAULT NULL,
  ROLE                 VARCHAR(20)  NOT NULL,
  GENDER               VARCHAR(10)  NULL     DEFAULT NULL,
  DESCRIPTION          VARCHAR(500) NULL     DEFAULT NULL,
  FIRST_NAME           VARCHAR(40)  NULL     DEFAULT NULL,
  LAST_NAME            VARCHAR(40)  NULL     DEFAULT NULL,
  PHONE                VARCHAR(25)  NULL     DEFAULT NULL,
  DATE_OF_BIRTH        DATE         NULL     DEFAULT NULL,
  IMAGE                VARCHAR(100) NULL     DEFAULT NULL,
  DATE_OF_REGISTRATION DATE         NOT NULL,
  LAST_ACTIVITY        DATE         NULL     DEFAULT NULL,
  HASH                 VARCHAR(20)  NULL     DEFAULT NULL,
  VK_ID                BIGINT(20)   NULL     DEFAULT NULL,
  FACEBOOK_ID          BIGINT(20)   NULL     DEFAULT NULL,
  GOOGLE_ID            BIGINT(20)   NULL     DEFAULT NULL,

  UNIQUE (EMAIL),
  PRIMARY KEY (USER_ID)
);


CREATE TABLE SPORT (
  SPORT_ID BIGINT(20)  NOT NULL AUTO_INCREMENT,
  NAME_EN  VARCHAR(40) NOT NULL,
  NAME_RU  VARCHAR(40) NOT NULL,

  UNIQUE (NAME_EN, NAME_RU),
  PRIMARY KEY (SPORT_ID)
);


CREATE TABLE MESSAGE (
  MESSAGE_ID     BIGINT(20)   NOT NULL AUTO_INCREMENT,
  USER_ID        BIGINT(20)   NOT NULL,
  AUTHOR_ID      BIGINT(20)   NULL     DEFAULT NULL,
  TITLE          VARCHAR(50)  NULL     DEFAULT NULL,
  TEXT           VARCHAR(800) NULL     DEFAULT NULL,
  TIME_OF_CREATE DATE         NOT NULL,
  TIME_OF_READ   DATE         NULL     DEFAULT NULL,

  PRIMARY KEY (MESSAGE_ID),
  CONSTRAINT FK_MESSAGE FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);


CREATE TABLE SCHEDULE (
  SCHEDULE_ID BIGINT(20) NOT NULL,
  USER_ID     BIGINT(20) NOT NULL,
  SPORT_ID    BIGINT(20) NULL     DEFAULT NULL,
  START_TIME  DATE       NULL     DEFAULT NULL,
  END_TIME    DATE       NULL     DEFAULT NULL,

  PRIMARY KEY (SCHEDULE_ID, USER_ID, SPORT_ID),
  CONSTRAINT FK_SCHEDULE_USER FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  CONSTRAINT FK_SCHEDULE_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID)
);


CREATE TABLE SKILL (
  SKILL_ID    BIGINT(20)  NOT NULL,
  USER_ID     BIGINT(20)  NOT NULL,
  SPORT_ID    BIGINT(20)  NOT NULL,
  SKILL_LEVEL VARCHAR(20) NOT NULL,

  PRIMARY KEY (SKILL_ID, USER_ID, SPORT_ID),
  CONSTRAINT FK_SKILL_USER FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  CONSTRAINT FK_SKILL_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID)
);

CREATE TABLE DAY (
  DAY_ID      BIGINT(20)  NOT NULL,
  SCHEDULE_ID BIGINT(20)  NOT NULL,
  DATE        DATE        NOT NULL,
  DAY_OF_WEEK VARCHAR(20) NOT NULL,

  PRIMARY KEY (DAY_ID),
  CONSTRAINT FK_DAY FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (SCHEDULE_ID)
);


CREATE TABLE WEEKDAY (
  WEEKDAY_ID  BIGINT(20)  NOT NULL,
  SCHEDULE_ID BIGINT(20)  NOT NULL,
  DAY_OF_WEEK VARCHAR(20) NOT NULL,

  PRIMARY KEY (WEEKDAY_ID),
  CONSTRAINT FK_WEEKDAY FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (SCHEDULE_ID)
);


CREATE TABLE USER_SPORT (
  USER_ID   BIGINT(20) NOT NULL,
  SPORT_ID  BIGINT(20) NOT NULL,

  PRIMARY KEY (USER_ID, SPORT_ID),
  CONSTRAINT FK_USER_SPORT FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  CONSTRAINT FK_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID)
);


CREATE TABLE USER_FAVORITE (
  USER_ID     BIGINT(20) NOT NULL,
  FAVORITE_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (USER_ID, FAVORITE_ID),
  CONSTRAINT FK_USER_FAVORITE FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  CONSTRAINT FK_FAVORITE FOREIGN KEY (FAVORITE_ID) REFERENCES USER (USER_ID)
);


CREATE INDEX IN_USER ON USER (USER_ID, EMAIL);
CREATE INDEX IN_SPORT ON SPORT (SPORT_ID, NAME_RU);
CREATE INDEX IN_SCHEDULE ON SCHEDULE (SCHEDULE_ID, USER_ID, SPORT_ID);
CREATE INDEX IN_SKILL ON SKILL (SKILL_ID, USER_ID, SPORT_ID);
CREATE INDEX IN_DAY ON DAY (DAY_ID, SCHEDULE_ID);
CREATE INDEX IN_WEEKDAY ON WEEKDAY (WEEKDAY_ID, SCHEDULE_ID);
CREATE INDEX IN_MESSAGE ON MESSAGE (MESSAGE_ID);



