CREATE TABLE USER (
  USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  SITY VARCHAR(50) NULL DEFAULT NULL,
  EMAIL VARCHAR(50) NULL DEFAULT NULL,
  ROLE VARCHAR(50) NOT NULL ,
  DESCRIPTION VARCHAR(250) NULL DEFAULT NULL,
  FRIST_NAME VARCHAR(250) NULL DEFAULT NULL,
  LAST_NAME VARCHAR(250) NULL DEFAULT NULL,
  PHONE VARCHAR(250) NULL DEFAULT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  PRIMARY KEY (USER_ID)
);


CREATE TABLE SPORT (
  SPORT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (SPORT_ID)
);


CREATE TABLE USER_SPORT (
  USER_ID BIGINT(20) NOT NULL,
  SPORT_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID, SPORT_ID),
  INDEX FK_SPORT (SPORT_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  CONSTRAINT FK_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID)
);

