CREATE TABLE FILM(
   ID INT,
   NAME VARCHAR(255),
   DESCRIPTION VARCHAR(255),
   PRIMARY KEY (ID));

   CREATE TABLE FILM_ORDER(
   ID INT,
   FILM_ID INT,
   CUSTOMER_NAME varchar(255),
   CUSTOMER_PHONE varchar(255),
   PRIMARY KEY (ID),
   FOREIGN KEY (FILM_ID) REFERENCES FILM(ID)
   );